service: nba-stats

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  eventBridge:
    useCloudFormation: true
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'sqs:ReceiveMessage'
            - 'sqs:SendMessage'
          Resource: !GetAtt Queue.Arn

functions:
  schedule:
    handler: handler_scheduleTasks.scheduleTasks
    events:
      - eventBridge:
          schedule: rate(10 minutes)
    environment:
      AWS_REGION: 'us-east-1'
      AWS_SQS_URL: !Ref Queue
      AWS_SQS_BATCH_SIZE: '10'

  task:
    handler: handler_task.task
    events:
      - sqs:
          arn: !GetAtt Queue.Arn
          batchSize: 10
    environment:
      AWS_CLOUDFRONT_DISTRIBUTION: 'E33WH3YYF53YOA'
      AWS_REGION: 'us-east-1'
      AWS_S3_BUCKET: 'basketball-stats-data'

resources:
  Resources:
    Queue: 
      Type: AWS::SQS::Queue
      Properties: 
        MessageRetentionPeriod: 700
